export type GameMode = 'principiante' | 'gossip' | 'picante' | 'hardcore' | 'descarado'

export interface GameModeConfig {
  id: GameMode
  name: string
  emoji: string
  description: string
  gradient: string
  accentColor: string
}

export const GAME_MODES: GameModeConfig[] = [
  {
    id: 'principiante',
    name: 'Principiante',
    emoji: '😄',
    description: 'La mejor forma de introducir a tus amigos en el juego. Preguntas divertidas y retos para ponerse a tono.',
    gradient: 'from-green-500 to-emerald-600',
    accentColor: 'text-emerald-400',
  },
  {
    id: 'gossip',
    name: 'Gossip Rueda',
    emoji: '🎡',
    description: 'De forma anónima cada uno escribe un chisme, una pregunta y un reto. La rueda se encarga del resto.',
    gradient: 'from-blue-500 to-violet-600',
    accentColor: 'text-blue-400',
  },
  {
    id: 'picante',
    name: 'Picante',
    emoji: '😈',
    description: 'Con retos locos y preguntas personales, un día para el recuerdo. Solo para los que se atreven.',
    gradient: 'from-orange-500 to-red-600',
    accentColor: 'text-orange-400',
  },
  {
    id: 'hardcore',
    name: 'Hardcore',
    emoji: '🔥',
    description: 'Preguntas y retos diseñados para crear máxima tensión. Puede haber discusiones.',
    gradient: 'from-red-600 to-rose-900',
    accentColor: 'text-red-400',
  },
  {
    id: 'descarado',
    name: 'Descarado',
    emoji: '😏',
    description: 'Diversión y energía positiva mientras descubres el resto. Atrévete a ser el más descarado.',
    gradient: 'from-pink-500 to-violet-600',
    accentColor: 'text-pink-400',
  },
]

export const QUESTIONS_BY_MODE: Record<GameMode, string[]> = {
  principiante: [
    '¿Quién es más probable que se quede dormido en una fiesta?',
    '¿Quién es más probable que llore viendo una película?',
    '¿Quién es más probable que se ría en el momento más inapropiado?',
    '¿Quién es más probable que tenga más de 5 alarmas por la mañana?',
    '¿Quién es más probable que sea el primero en irse a dormir?',
    '¿Quién es más probable que gaste todo su dinero en comida?',
    '¿Quién es más probable que se pierda en una ciudad nueva?',
    '¿Quién es más probable que llore en un concierto?',
    '¿Quién es más probable que siga a una celebridad de forma obsesiva?',
    '¿Quién es más probable que repita ropa sin lavarse?',
    '¿Quién es más probable que se olvide de dónde aparcó el coche?',
    '¿Quién es más probable que haga spoiler sin darse cuenta?',
    '¿Quién es más probable que se caiga al entrar en una habitación?',
    '¿Quién es más probable que hable solo en voz alta?',
    '¿Quién es más probable que baile en su habitación a solas?',
    '¿Quién es más probable que tenga un peluche escondido en su cuarto?',
    '¿Quién es más probable que se ponga nervioso hablando en público?',
    '¿Quién es más probable que tarde más de 30 minutos duchándose?',
    '¿Quién es más probable que se coma el postre antes que el plato principal?',
    '¿Quién es más probable que haya llamado "mamá" a un profesor por error?',
    '¿Quién es más probable que tenga más de 500 apps instaladas?',
    '¿Quién es más probable que haya enviado un audio a la persona equivocada?',
    '¿Quién es más probable que se quede mirando el móvil sin hacer nada?',
    '¿Quién es más probable que recuerde la letra de canciones que ya nadie escucha?',
    '¿Quién es más probable que llegue tarde siempre?',
  ],

  gossip: [
    '¿Quién es más probable que tenga más secretos sobre el grupo?',
    '¿Quién es más probable que sea el chismoso oficial del grupo?',
    '¿Quién es más probable que haya contado algo que le dijeron en secreto?',
    '¿Quién es más probable que sepa algo de todos sin que los demás lo sepan?',
    '¿Quién es más probable que haya hablado mal de alguien del grupo?',
    '¿Quién es más probable que guarde el secreto mejor?',
    '¿Quién es más probable que haya creado un rumor sin querer?',
    '¿Quién es más probable que tenga un grupo de chat secreto?',
    '¿Quién es más probable que sepa lo que hace todo el mundo?',
    '¿Quién es más probable que haya cotilleado con la familia de alguien del grupo?',
    '¿Quién es más probable que se entere de las noticias del grupo antes que nadie?',
    '¿Quién es más probable que haya exagerado una historia para hacerla más dramática?',
    '¿Quién es más probable que sepa quién le gusta a quién en el grupo?',
    '¿Quién es más probable que guarde mensajes comprometedores de alguien?',
    '¿Quién es más probable que haya pasado capturas de pantalla de conversaciones privadas?',
    '¿Quién es más probable que sepa un secreto que podría cambiar todo?',
    '¿Quién es más probable que haya mentido en este grupo y no lo hayamos descubierto?',
    '¿Quién es más probable que haya inventado una excusa para cubrir a alguien del grupo?',
    '¿Quién es más probable que investigue las redes sociales de los demás más seguido?',
    '¿Quién es más probable que conozca la historia completa detrás de algo que "no entendemos"?',
    '¿Quién es más probable que sepa lo que hace cada uno fuera del grupo?',
    '¿Quién es más probable que haya descubierto algo de alguien por accidente?',
    '¿Quién es más probable que recuerde todo lo que se ha contado en el grupo?',
    '¿Quién es más probable que haya compartido algo del grupo con alguien de fuera?',
    '¿Quién es más probable que sea la fuente de los chismes del grupo?',
  ],

  picante: [
    '¿Quién es más probable que envíe un mensaje a su ex a las 3 AM?',
    '¿Quién es más probable que tenga una app de citas secreta?',
    '¿Quién es más probable que haya besado a alguien del grupo?',
    '¿Quién es más probable que tenga un crush secreto en el grupo?',
    '¿Quién es más probable que haya dicho "te quiero" sin sentirlo?',
    '¿Quién es más probable que haya hecho ghosting a alguien?',
    '¿Quién es más probable que haya espiado el teléfono de su pareja?',
    '¿Quién es más probable que haya ligado con alguien de la familia de un amigo?',
    '¿Quién es más probable que haya dado un número falso en una discoteca?',
    '¿Quién es más probable que haya mentido sobre su edad a alguien que le gustaba?',
    '¿Quién es más probable que tenga conversaciones íntimas que no debería?',
    '¿Quién es más probable que haya coqueteado con alguien en una relación?',
    '¿Quién es más probable que haya usado a alguien solo por interés?',
    '¿Quién es más probable que haya tenido un sueño con alguien del grupo?',
    '¿Quién es más probable que tenga fotos comprometedoras en el teléfono?',
    '¿Quién es más probable que haya enviado un mensaje picante al destinatario equivocado?',
    '¿Quién es más probable que haya fingido una relación para dar celos?',
    '¿Quién es más probable que haya besado a alguien en el primer encuentro?',
    '¿Quién es más probable que tenga una historia que no le ha contado a nadie?',
    '¿Quién es más probable que haya tenido una relación con alguien mucho mayor?',
    '¿Quién es más probable que haya coqueteado con el ex de un amigo?',
    '¿Quién es más probable que haya bloqueado y desbloqueado a alguien más de 3 veces?',
    '¿Quién es más probable que tenga más de una persona interesada en él/ella ahora mismo?',
    '¿Quién es más probable que haya actuado interesado/a sin estarlo?',
    '¿Quién es más probable que haya tenido algo con alguien del trabajo o la clase?',
  ],

  hardcore: [
    '¿Quién es más probable que haya robado algo (aunque sea pequeño)?',
    '¿Quién es más probable que haya mentido en una situación muy importante?',
    '¿Quién es más probable que haya traicionado a un amigo?',
    '¿Quién es más probable que tenga una vida doble que nadie conoce?',
    '¿Quién es más probable que haya dicho algo muy cruel a alguien?',
    '¿Quién es más probable que haya hecho trampa en un examen?',
    '¿Quién es más probable que guarde un secreto que podría destrozar algo?',
    '¿Quién es más probable que haya engañado a alguien en una relación?',
    '¿Quién es más probable que tenga deudas que nadie conoce?',
    '¿Quién es más probable que haya hecho algo de lo que se avergüenza profundamente?',
    '¿Quién es más probable que haya destruido una amistad por su culpa?',
    '¿Quién es más probable que haya mentido al grupo sobre algo importante?',
    '¿Quién es más probable que haya hecho algo ilegal sin que nadie lo sepa?',
    '¿Quién es más probable que tenga un secreto que cambiaría la opinión del grupo?',
    '¿Quién es más probable que haya puesto a dos personas en contra la una de la otra?',
    '¿Quién es más probable que haya tomado dinero sin permiso?',
    '¿Quién es más probable que tenga rencor hacia alguien del grupo?',
    '¿Quién es más probable que haya bloqueado a alguien por miedo a la verdad?',
    '¿Quién es más probable que haya hecho algo que nadie en este grupo aprobaría?',
    '¿Quién es más probable que haya fingido ser alguien que no es durante mucho tiempo?',
    '¿Quién es más probable que haya creado un problema y dejado que otro cargara la culpa?',
    '¿Quién es más probable que sepa que está haciendo algo mal y lo siga haciendo?',
    '¿Quién es más probable que haya usado la confianza de alguien en su contra?',
    '¿Quién es más probable que tenga algo pendiente que nunca ha podido admitir?',
    '¿Quién es más probable que haya ignorado a alguien que lo necesitaba?',
  ],

  descarado: [
    '¿Quién es más probable que diga lo que piensa sin ningún filtro?',
    '¿Quién es más probable que haga una apuesta ridícula y la cumpla?',
    '¿Quién es más probable que baile sobre una mesa esta noche?',
    '¿Quién es más probable que haga algo espontáneo y loco esta semana?',
    '¿Quién es más probable que se atreva a hablarle a un desconocido?',
    '¿Quién es más probable que haga el ridículo sin importarle nada?',
    '¿Quién es más probable que acepte cualquier reto sin pensarlo?',
    '¿Quién es más probable que haga una entrada dramática a una fiesta?',
    '¿Quién es más probable que convenza a todos de hacer algo loco?',
    '¿Quién es más probable que grite algo en público?',
    '¿Quién es más probable que use ropa llamativa en un evento formal?',
    '¿Quién es más probable que llegue a un evento sin invitación?',
    '¿Quién es más probable que proponga un plan de última hora que salga genial?',
    '¿Quién es más probable que se meta en conversaciones de desconocidos?',
    '¿Quién es más probable que haga una tontería solo para hacer reír al grupo?',
    '¿Quién es más probable que sea el primero en probar algo nuevo?',
    '¿Quién es más probable que haga una actuación improvisada?',
    '¿Quién es más probable que se vuelva el alma de la fiesta sin proponérselo?',
    '¿Quién es más probable que proponga jugar a algo que acabe siendo un desastre divertido?',
    '¿Quién es más probable que diga un piropo a un desconocido?',
    '¿Quién es más probable que haga una foto random a alguien en la calle?',
    '¿Quién es más probable que se meta de lleno en el grupo de música de una fiesta?',
    '¿Quién es más probable que le pida número a alguien que acaba de conocer?',
    '¿Quién es más probable que organice la noche más memorable del grupo?',
    '¿Quién es más probable que se atreva a hacer algo que los demás no harían nunca?',
  ],
}

export const CONSEQUENCES: string[] = [
  'Toma 3 sorbos',
  'Muestra el último mensaje que enviaste',
  'Confiesa algo que nunca has contado al grupo',
  'Imita a alguien del grupo durante 30 segundos',
  'Muestra la última foto que tomaste',
  'Toma 5 sorbos',
  'Di algo que no te gusta de la persona a tu izquierda',
  'Muestra el último meme que enviaste',
  'Haz 10 sentadillas ahora mismo',
  'Canta una canción durante 15 segundos',
  'El grupo decide tu consecuencia',
  'Toma 2 sorbos por cada voto que recibiste',
  'Muestra tu búsqueda más reciente en Google',
  'Di el nombre de tu último crush',
  'Baila sin música durante 15 segundos',
  'Muestra el último GIF que enviaste',
  'Escribe un mensaje raro a alguien de tus contactos y envíalo',
  'El de tu izquierda elige tu consecuencia',
  'Toma 4 sorbos',
  'Cuenta el mejor secreto que sabes del grupo',
]

export function getConsequence(roomId: string, round: number): string {
  let hash = 0
  const str = `${roomId}-${round}`
  for (let i = 0; i < str.length; i++) {
    hash = ((hash << 5) - hash) + str.charCodeAt(i)
    hash = hash & hash
  }
  return CONSEQUENCES[Math.abs(hash) % CONSEQUENCES.length]
}
